# Placeholder for a team that isn't decided yet (e.g. a knockout opponent the
# source API still reports as null). Kept here so sync and the DB filters agree.
TBD_TEAM = "Ожидается"
# Titles that mean "no real fixture yet" — filtered out of listings. Includes the
# legacy "None vs None" so rows synced before this change stay hidden until re-synced.
EMPTY_TITLES = ("None vs None", f"{TBD_TEAM} vs {TBD_TEAM}")


def _f(code: str) -> str:
    """ISO 3166-1 alpha-2 → flag emoji."""
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in code.upper())


# Subdivision flags (England / Scotland / Wales have no ISO alpha-2 code).
_ENG = "\U0001f3f4\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f"
_SCO = "\U0001f3f4\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f"
_WAL = "\U0001f3f4\U000e0067\U000e0062\U000e0077\U000e006c\U000e0073\U000e007f"

# Maps football-data.org shortName / name → flag emoji.
# Add variations (old names, aliases) so missing flags are rare.
_FLAGS: dict[str, str] = {
    # ── CONMEBOL ──────────────────────────────────────────────
    "Argentina": _f("AR"),
    "Brazil": _f("BR"),
    "Uruguay": _f("UY"),
    "Colombia": _f("CO"),
    "Ecuador": _f("EC"),
    "Paraguay": _f("PY"),
    "Venezuela": _f("VE"),
    "Bolivia": _f("BO"),
    "Chile": _f("CL"),
    "Peru": _f("PE"),
    # ── CONCACAF ──────────────────────────────────────────────
    "USA": _f("US"),
    "United States": _f("US"),
    "Mexico": _f("MX"),
    "Canada": _f("CA"),
    "Panama": _f("PA"),
    "Costa Rica": _f("CR"),
    "Honduras": _f("HN"),
    "Jamaica": _f("JM"),
    "Guatemala": _f("GT"),
    "Haiti": _f("HT"),
    "El Salvador": _f("SV"),
    "Cuba": _f("CU"),
    "Trinidad & Tobago": _f("TT"),
    "Trinidad and Tobago": _f("TT"),
    "Suriname": _f("SR"),
    "Curaçao": _f("CW"),
    "Curacao": _f("CW"),
    "Belize": _f("BZ"),
    "Nicaragua": _f("NI"),
    "Dominican Rep.": _f("DO"),
    "Dominican Republic": _f("DO"),
    "Antigua and Barbuda": _f("AG"),
    "Barbados": _f("BB"),
    "Guyana": _f("GY"),
    # ── UEFA ──────────────────────────────────────────────────
    "Germany": _f("DE"),
    "Spain": _f("ES"),
    "France": _f("FR"),
    "England": _ENG,
    "Portugal": _f("PT"),
    "Netherlands": _f("NL"),
    "Belgium": _f("BE"),
    "Croatia": _f("HR"),
    "Switzerland": _f("CH"),
    "Denmark": _f("DK"),
    "Austria": _f("AT"),
    "Poland": _f("PL"),
    "Serbia": _f("RS"),
    "Hungary": _f("HU"),
    "Scotland": _SCO,
    "Wales": _WAL,
    "Turkey": _f("TR"),
    "Türkiye": _f("TR"),
    "Ukraine": _f("UA"),
    "Romania": _f("RO"),
    "Greece": _f("GR"),
    "Czech Republic": _f("CZ"),
    "Czechia": _f("CZ"),
    "Slovakia": _f("SK"),
    "Norway": _f("NO"),
    "Sweden": _f("SE"),
    "Finland": _f("FI"),
    "Albania": _f("AL"),
    "Slovenia": _f("SI"),
    "Iceland": _f("IS"),
    "Bosnia-Herzegovina": _f("BA"),
    "Bosnia": _f("BA"),
    "North Macedonia": _f("MK"),
    "Kosovo": _f("XK"),
    "Montenegro": _f("ME"),
    "Georgia": _f("GE"),
    "Bulgaria": _f("BG"),
    "Republic of Ireland": _f("IE"),
    "Ireland": _f("IE"),
    "Northern Ireland": _f("GB"),
    "Israel": _f("IL"),
    "Cyprus": _f("CY"),
    "Estonia": _f("EE"),
    "Latvia": _f("LV"),
    "Lithuania": _f("LT"),
    "Kazakhstan": _f("KZ"),
    "Armenia": _f("AM"),
    "Azerbaijan": _f("AZ"),
    "Belarus": _f("BY"),
    "Moldova": _f("MD"),
    "Luxembourg": _f("LU"),
    "Andorra": _f("AD"),
    "Malta": _f("MT"),
    "Faroe Islands": _f("FO"),
    "Gibraltar": _f("GI"),
    "Liechtenstein": _f("LI"),
    "San Marino": _f("SM"),
    # ── CAF ───────────────────────────────────────────────────
    "Morocco": _f("MA"),
    "Senegal": _f("SN"),
    "Nigeria": _f("NG"),
    "Egypt": _f("EG"),
    "Ghana": _f("GH"),
    "Ivory Coast": _f("CI"),
    "Côte d'Ivoire": _f("CI"),
    "Cote d'Ivoire": _f("CI"),
    "Algeria": _f("DZ"),
    "Cameroon": _f("CM"),
    "Tunisia": _f("TN"),
    "South Africa": _f("ZA"),
    "Mali": _f("ML"),
    "DR Congo": _f("CD"),
    "Congo DR": _f("CD"),
    "Tanzania": _f("TZ"),
    "Burkina Faso": _f("BF"),
    "Benin": _f("BJ"),
    "Zimbabwe": _f("ZW"),
    "Zambia": _f("ZM"),
    "Cape Verde": _f("CV"),
    "Comoros": _f("KM"),
    "Gabon": _f("GA"),
    "Mozambique": _f("MZ"),
    "Angola": _f("AO"),
    "Kenya": _f("KE"),
    "Uganda": _f("UG"),
    "Namibia": _f("NA"),
    "Guinea": _f("GN"),
    "Eq. Guinea": _f("GQ"),
    "Equatorial Guinea": _f("GQ"),
    "Congo": _f("CG"),
    "Mauritania": _f("MR"),
    "Libya": _f("LY"),
    "Sudan": _f("SD"),
    "Rwanda": _f("RW"),
    "Ethiopia": _f("ET"),
    "Malawi": _f("MW"),
    "Togo": _f("TG"),
    "Botswana": _f("BW"),
    "Madagascar": _f("MG"),
    "Niger": _f("NE"),
    "Liberia": _f("LR"),
    "Sierra Leone": _f("SL"),
    "Guinea-Bissau": _f("GW"),
    "Somalia": _f("SO"),
    "Seychelles": _f("SC"),
    "Eswatini": _f("SZ"),
    "Swaziland": _f("SZ"),
    "Lesotho": _f("LS"),
    # ── AFC ───────────────────────────────────────────────────
    "Japan": _f("JP"),
    "South Korea": _f("KR"),
    "Korea Republic": _f("KR"),
    "Korea DPR": _f("KP"),
    "North Korea": _f("KP"),
    "Australia": _f("AU"),
    "Iran": _f("IR"),
    "Saudi Arabia": _f("SA"),
    "Qatar": _f("QA"),
    "Iraq": _f("IQ"),
    "Jordan": _f("JO"),
    "Uzbekistan": _f("UZ"),
    "Oman": _f("OM"),
    "Bahrain": _f("BH"),
    "Kuwait": _f("KW"),
    "Palestine": _f("PS"),
    "UAE": _f("AE"),
    "United Arab Emirates": _f("AE"),
    "China PR": _f("CN"),
    "China": _f("CN"),
    "Thailand": _f("TH"),
    "Vietnam": _f("VN"),
    "Indonesia": _f("ID"),
    "Philippines": _f("PH"),
    "Kyrgyzstan": _f("KG"),
    "Tajikistan": _f("TJ"),
    "India": _f("IN"),
    "Hong Kong": _f("HK"),
    "Malaysia": _f("MY"),
    "Singapore": _f("SG"),
    "Myanmar": _f("MM"),
    "Lebanon": _f("LB"),
    "Syria": _f("SY"),
    "Nepal": _f("NP"),
    "Pakistan": _f("PK"),
    "Bangladesh": _f("BD"),
    "Afghanistan": _f("AF"),
    "Maldives": _f("MV"),
    "Yemen": _f("YE"),
    # ── OFC ───────────────────────────────────────────────────
    "New Zealand": _f("NZ"),
    "Fiji": _f("FJ"),
    "Papua New Guinea": _f("PG"),
    "Solomon Islands": _f("SB"),
    "Vanuatu": _f("VU"),
    "Tahiti": _f("PF"),
    "New Caledonia": _f("NC"),
    "Samoa": _f("WS"),
    "American Samoa": _f("AS"),
    "Cook Islands": _f("CK"),
    "Tonga": _f("TO"),
}


def get_flag(team_name: str) -> str:
    """Return flag emoji for a team name, or empty string if unknown."""
    return _FLAGS.get(team_name.strip(), "")


def flagged(title: str) -> str:
    """Add flag emojis to a 'Home vs Away' title string."""
    parts = title.split(" vs ", 1)
    if len(parts) != 2:
        return title
    home, away = parts[0].strip(), parts[1].strip()
    hf, af = get_flag(home), get_flag(away)
    home_str = f"{hf} {home}" if hf else home
    away_str = f"{af} {away}" if af else away
    return f"{home_str} vs {away_str}"
